### ISSUE TITLE
Docs aren't on library.elm-lang.org

### ISSUE THREAD

**Issue by maxsnew** [mgold/elm-multiset#1]
For some reason there's no documentation here: http://library.elm-lang.org/packages/mgold/Elm-Multiset/1.0.0 despite the fact that it looks documented in the src.

**Comment by mgold** [comment]
Indeed they are not. `elm-doc Multiset.elm` seems to work fine. Pushing a new version doesn't fix the problem, so it wasn't a glitch in an earlier version of the package site. So, I have no idea what's going on, and therefore could use your help.

**Comment by maxsnew** [comment]
I would report a bug on the package website repo. I don't know enough about its implementation to have an idea what the bug is.

**Comment by mgold** [comment]
Done. By the way, have you found the library helpful?

**Comment by maxsnew** [comment]
I haven't used it. I just saw it and was curious to see how it was implemented and I found the docs not working.

**Comment by jvoigtlaender** [comment]
Seems to be fixed on http://package.elm-lang.org:1234.
